[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
authors = [
   { name = "Jeffrey Xiang", email = "jjx5@cornell.edu"},
]
name = "boltzmann_generator_7870"
version = "0.0.1"
dependencies = [
    "numpy",
    "torch",
    "lightning",
    "matplotlib",
]